myapp/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('showtable/', views.show_table, name='show_table'),
    path('insert/', views.choose_table_insert, name='choose_table_insert'),
    path('insert/<str:table>/', views.insert_table, name='insert_table'),
    path('insert/project/', views.insert_table, name='new_project'),  
    path('delete/', views.delete_object, name='delete_object'),
    path('get_attributes/', views.get_attributes, name='get_attributes'),
    path('get/', views.get_object, name='get_object'),
    path('update/', views.choose_object, name='choose_object'),
    path('update/<str:table>/<str:attribute>/<str:value>/', views.update_object, name='update_object'),
    path('report/', views.generate_report, name='choose_project'), 
    path('report/<int:project_id>/', views.report, name='report'),
    path('export/<int:project_id>/', views.export_pdf, name="export_pdf" ),
    path('<str:table>/<int:id>/', views.manage, name='manage'),
]

project_management/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
]

myapp/forms.py
from django import forms
from .models import Employee, Project, ProjectTeam, Budget, Invoice, Activity, Task, Expense, Deliverable, ProjectTeamEmployee

class ProjectSelectionForm(forms.Form):
    project = forms.ModelChoiceField(queryset=Project.objects.all(), label='Select Project', empty_label="---Choose Project---")


class TableFormIns(forms.Form):
    TABLE_CHOICES = [
        ('', '---Choose Table---'),
        ('Employee', 'Employee'),
        ('Project', 'Project'),
        ('ProjectTeam', 'Project Team'),
        ('Budget', 'Budget'),
        ('Invoice', 'Invoice'),
        ('Activity', 'Activity'),
        ('Task', 'Task'),
        ('Expense', 'Expense'),
        ('Deliverable', 'Deliverable'),
        ('ProjectTeamEmployee', 'Add employee to team'),
    ]

    table = forms.ChoiceField(label='Table', choices=TABLE_CHOICES)

class TableForm(forms.Form):
    TABLE_CHOICES = [
        ('', '---Choose Table---'),
        ('Employee', 'Employee'),
        ('Project', 'Project'),
        ('ProjectTeam', 'Project Team'),
        ('Budget', 'Budget'),
        ('Invoice', 'Invoice'),
        ('Activity', 'Activity'),
        ('Task', 'Task'),
        ('Expense', 'Expense'),
        ('Deliverable', 'Deliverable'),
        ('ProjectTeamEmployee', 'Employee in team'),
    ]

    table = forms.ChoiceField(label='Table', choices=TABLE_CHOICES)

class GetInp(forms.Form):
    TABLE_CHOICES = [
        ('', '---Choose Table---'),
        ('Employee', 'Employee'),
        ('Project', 'Project'),
        ('ProjectTeam', 'Project Team'),
        ('Budget', 'Budget'),
        ('Invoice', 'Invoice'),
        ('Activity', 'Activity'),
        ('Task', 'Task'),
        ('Expense', 'Expense'),
        ('Deliverable', 'Deliverable'),
        ('ProjectTeamEmployee', 'Employee in team'),
    ]
    table = forms.ChoiceField(label='Table', choices=TABLE_CHOICES)
    attribute = forms.ChoiceField(label='Attribute', choices=[], required=True)
    value = forms.CharField(label='Value', max_length=50, widget=forms.TextInput, required=True)

class InsertForm(forms.Form):
    def __init__(self, *args, table_fields=None, **kwargs):
        super(InsertForm, self).__init__(*args, **kwargs)
        if table_fields:
            for field_name, field_type in table_fields.items():
                field_name = field_name.replace('_', ' ')
                if field_type == 'CharField':
                    self.fields[field_name] = forms.CharField(label=field_name, max_length=255)
                elif field_type == 'EmailField':
                    self.fields[field_name] = forms.EmailField(label=field_name, max_length=255)
                elif field_type == 'IntegerField':
                    self.fields[field_name] = forms.IntegerField(label=field_name)
                elif field_type == 'ForeignKey':
                    self.fields[field_name] = forms.IntegerField(label=field_name)
                elif field_type == 'DateField':
                    self.fields[field_name] = forms.DateField(label=field_name)
                elif field_type == 'TextField':
                    self.fields[field_name] = forms.CharField(label=field_name, widget=forms.Textarea)
                elif field_type == 'DecimalField':
                    self.fields[field_name] = forms.DecimalField(label=field_name, max_digits=15, decimal_places=2)

class UpdateForm(forms.Form):
    def __init__(self, *args, table_fields=None, **kwargs):
        super(UpdateForm, self).__init__(*args, **kwargs)
        if table_fields:
            for field_name, field_type in table_fields.items():
                field_name = field_name.replace('_', ' ')
                if field_type == 'CharField':
                    self.fields[field_name] = forms.CharField(label=field_name, max_length=255, required=False)
                elif field_type == 'EmailField':
                    self.fields[field_name] = forms.EmailField(label=field_name, max_length=255, required=False)
                elif field_type == 'IntegerField':
                    self.fields[field_name] = forms.IntegerField(label=field_name, required=False)
                elif field_type == 'ForeignKey':
                    self.fields[field_name] = forms.IntegerField(label=field_name, required=False)
                elif field_type == 'DateField':
                    self.fields[field_name] = forms.DateField(label=field_name, required=False)
                elif field_type == 'TextField':
                    self.fields[field_name] = forms.CharField(label=field_name, widget=forms.Textarea, required=False)
                elif field_type == 'DecimalField':
                    self.fields[field_name] = forms.DecimalField(label=field_name, max_digits=15, decimal_places=2, required=False)

myapp/views.py
import json
from django.http import JsonResponse, HttpResponseNotAllowed, HttpResponseBadRequest, HttpResponse
from .models import Employee, Project, ProjectTeam, Budget, Invoice, Activity, Task, Expense, Deliverable, ProjectTeamEmployee
from myapp.forms import GetInp, InsertForm, TableForm, UpdateForm, TableFormIns, ProjectSelectionForm
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from xhtml2pdf import pisa

model_map = {
    'employee': Employee,
    'project': Project,
    'projectteam': ProjectTeam,
    'budget': Budget,
    'invoice': Invoice,
    'activity': Activity,
    'task': Task,
    'expense': Expense,
    'deliverable': Deliverable,
    'projectteamemployee': ProjectTeamEmployee,
}

def manage(request, table, id):
    context = {}
    not_displayed_keys = ['Project', 'Budget', 'Activity', 'Employee', 'Expense']
    context['displayed_keys'] = not_displayed_keys
    context['table'] = table.replace('_', ' ')
    if table == 'Project':
        project = get_object_or_404(Project, project_id=id)
        activities = Activity.objects.filter(project_id=project)
        budgets = Budget.objects.filter(project_id=id)
        derivables = Deliverable.objects.filter(project_id=id)
        project_team = ProjectTeam.objects.get(project_id=project)
        project_team_employees_ids = ProjectTeamEmployee.objects.filter(team_id=project_team).values_list('employee_id', flat=True)
        employees = Employee.objects.filter(employee_id__in=project_team_employees_ids)

        related_employees=[]
        related_activities = [[(field_name.replace('_', ' '), value) for field_name, value in activity.__dict__.items()][1:] for activity in activities]
        related_budgets = [[(field_name.replace('_', ' '), value) for field_name, value in budget.__dict__.items()][1:] for budget in budgets]
        related_employees = [[(field_name.replace('_', ' '), value) for field_name, value in employee.__dict__.items()][1:] for employee in employees]
        related_derivables = [[(field_name.replace('_', ' '), value) for field_name, value in derivable.__dict__.items()][1:] for derivable in derivables]
        
        context['entity'] = [(field_name.replace('_', ' '), value) for field_name, value in project.__dict__.items()][1:]
        context['Team'] = [(field_name.replace('_', ' '), value) for field_name, value in project_team.__dict__.items()][1:]
        context['related_entities'] = {
            'Activity': related_activities,
            'Budget': related_budgets,
            'Employee': related_employees,
            'Derivable': related_derivables,
        }

    elif table == 'Activity':
        activity = get_object_or_404(Activity, activity_id=id)
        tasks = Task.objects.filter(activity_id=id)
        related_tasks = [[(field_name.replace('_', ' '), value) for field_name, value in task.__dict__.items()][1:] for task in tasks]
        context['entity'] = [(field_name.replace('_', ' '), value) for field_name, value in activity.__dict__.items()][1:]
        context['related_entities'] = {
            'Task': related_tasks,
        }

    elif table == 'Budget':
        budget = get_object_or_404(Budget, budget_id=id)
        expenses = Expense.objects.filter(budget_id=id)
        related_expenses = [[(field_name.replace('_', ' '), value) for field_name, value in expense.__dict__.items()][1:] for expense in expenses]
        context['entity'] = [(field_name.replace('_', ' '), value) for field_name, value in budget.__dict__.items()][1:]
        context['related_entities'] = {
            'Expense': related_expenses,
        }

    elif table == 'Employee':
        employee = get_object_or_404(Employee, employee_id=id)
        tasks = Task.objects.filter(responsible=id)
        related_tasks = [[(field_name.replace('_', ' '), value) for field_name, value in task.__dict__.items()][1:] for task in tasks]
        context['entity'] = [(field_name.replace('_', ' '), value) for field_name, value in employee.__dict__.items()][1:]
        context['related_entities'] = {
            'Task': related_tasks,
        }

    elif table == 'Expense':
        expense = get_object_or_404(Expense, expense_id=id)
        tasks = Task.objects.filter(task_id=expense.task_id)
        invoices = Invoice.objects.filter(invoice_id=expense.invoice_id)
        related_tasks = [[(field_name.replace('_', ' '), value) for field_name, value in task.__dict__.items()][1:] for task in tasks]
        related_invoice = [[(field_name.replace('_', ' '), value) for field_name, value in invoice.__dict__.items()][1:] for invoice in invoices]
        context['entity'] = [(field_name.replace('_', ' '), value) for field_name, value in expense.__dict__.items()][1:]
        context['related_entities'] = {
            'Task': related_tasks,
            'Invoice':related_invoice,
        }

    return render(request, 'manage.html', context)

def export_pdf(request, project_id):
    project = Project.objects.get(pk=project_id)
    try:
        project_team = ProjectTeam.objects.get(project_id=project)
    except Exception as e:
        project_team = None
    try:
        ProjectTeamEmployee_set=ProjectTeamEmployee.objects.filter(team_id=project_team.pk)
        project_team_employees_ids = ProjectTeamEmployee_set.values_list('employee_id', flat=True)
        project_team_employees = Employee.objects.filter(employee_id__in=project_team_employees_ids)
    except Exception as e:
            project_team_employees = None
    try:
        activities = Activity.objects.filter(project=project)
    except Exception as e:
        activities = None
    try:
        activities_id = activities.values_list('activity_id', flat=True)
        tasks = Task.objects.filter(activity_id__in=activities_id)
    except Exception as e:
        tasks = None

    try:
        budget = Budget.objects.get(project_id=project)
    except Exception as e:
        budget = None
    try:
        expenses = Expense.objects.filter(budget=budget.pk)
    except Exception as e:
        expenses = None
    try:    
        deliverables = Deliverable.objects.filter(project_id=project)
    except Exception as e:
        deliverables = None
    context = {
        'project': project,
        'project_team': project_team,
        'activities': activities,
        'budget': budget,
        'expenses': expenses,
        'deliverables': deliverables,
        'project_team_employees': project_team_employees,
        'tasks_act': tasks,
    }
    html = render_to_string("report.html", context)

    pdf_file = HttpResponse(content_type='application/pdf')
    pdf_file['Content-Disposition'] = 'attachment; filename="report.pdf"'

    pisa.CreatePDF(html, dest=pdf_file)

    return pdf_file

def report(request, project_id):
    project = Project.objects.get(pk=project_id)
    try:
        project_team = ProjectTeam.objects.get(project_id=project)
    except Exception as e:
        project_team = None
    try:
        ProjectTeamEmployee_set=ProjectTeamEmployee.objects.filter(team_id=project_team.pk)
        project_team_employees_ids = ProjectTeamEmployee_set.values_list('employee_id', flat=True)
        project_team_employees = Employee.objects.filter(employee_id__in=project_team_employees_ids)
    except Exception as e:
            project_team_employees = None
    try:
        activities = Activity.objects.filter(project=project)
    except Exception as e:
        activities = None
    try:
        activities_id = activities.values_list('activity_id', flat=True)
        tasks = Task.objects.filter(activity_id__in=activities_id)
    except Exception as e:
        tasks = None

    try:
        budget = Budget.objects.get(project_id=project)
    except Exception as e:
        budget = None
    try:
        expenses = Expense.objects.filter(budget=budget.pk)
    except Exception as e:
        expenses = None
    try:    
        deliverables = Deliverable.objects.filter(project_id=project)
    except Exception as e:
        deliverables = None
    context = {
        'project': project,
        'project_team': project_team,
        'activities': activities,
        'budget': budget,
        'expenses': expenses,
        'deliverables': deliverables,
        'project_team_employees': project_team_employees,
        'tasks_act': tasks,
    }
    return render(request, 'report.html', context)

def generate_report(request):
    if request.method == 'POST':
        form = ProjectSelectionForm(request.POST)
        if form.is_valid():
            project_id = form.cleaned_data['project'].pk
            return redirect('report', project_id=project_id)
    else:
        form = ProjectSelectionForm()
    return render(request, 'generate_report.html', {'form': form})

def home(request):
    projects = Project.objects.all()
    obj_values = []
    field_names = [field.name for field in Project._meta.fields]
    for project in projects:
        values = [(field_name, getattr(project, field_name)) for field_name in field_names]
        obj_values.append(values)
    return render(request, 'home.html', {'projects': projects, 'obj_values': obj_values})

def about(request):
    return render(request, 'about.html')

def show_table(request):
    if request.method == 'GET':
        form = TableForm(request.GET)
        if form.is_valid():
            table = form.cleaned_data['table']
            model = model_map.get(table.lower())
            if not model:
                return render(request, 'error.html', {'error_message': f"Table {table} not found"})
            try:
                obj = model.objects.all()
                field_names = [field.name for field in model._meta.fields]

myapp/templates/about.html
{% extends 'base.html' %}

{% block title %}
About
{% endblock %}

{% block content %}
<div class="container" style="text-align: center;">
    <h1>About Project Management Application</h1>
    <p>
        Welcome to our Project Management Application, a comprehensive tool designed to help you efficiently manage your projects from start to finish. Our platform offers a range of features that cater to the diverse needs of project managers, team members, and stakeholders.
    </p>
    <p>
        Our application streamlines project management by offering a user-friendly interface, allowing for easy navigation and efficient data handling. Whether you are managing a small team or a large enterprise, our tool is designed to help you achieve your project goals effectively.
    </p>
    <p>
        We continuously strive to improve our platform, and your feedback is invaluable to us. Please feel free to reach out with any suggestions or issues you encounter.
    </p>
    <p>
        Thank you for choosing our Project Management Application. We look forward to helping you succeed in your projects.
    </p>
    <h3>Key Features</h3>
    <div class="features-list" style="margin-bottom: 20px;">
        <div class="feature-item" style="margin-bottom: 10px;">
            <h4>Home</h4>
            <p>View an overview of all projects, including their current status and details.</p>
        </div>
        <div class="feature-item" style="margin-bottom: 10px;">
            <h4>View Table</h4>
            <p>Access detailed views of various project-related tables such as employees, tasks, budgets, and more.</p>
        </div>
        <div class="feature-item" style="margin-bottom: 10px;">
            <h4>Insert</h4>
            <p>Add new entries to different tables, facilitating the creation of projects, tasks, budgets, and other entities.</p>
        </div>
        <div class="feature-item" style="margin-bottom: 10px;">
            <h4>Get</h4>
            <p>Retrieve attributes from specified tables, making it easier to find and display specific information.</p>
        </div>
        <div class="feature-item" style="margin-bottom: 10px;">
            <h4>Update</h4>
            <p>Modify existing entries in any table to keep information up-to-date and accurate.</p>
        </div>
        <div class="feature-item" style="margin-bottom: 10px;">
            <h4>Delete</h4>
            <p>Remove entries from tables that are no longer needed or were added in error.</p>
        </div>
        <div class="feature-item" style="margin-bottom: 10px;">
            <h4>New Project</h4>
            <p>Initiate new projects with all necessary details and assign team members.</p>
        </div>
        <div class="feature-item" style="margin-bottom: 10px;">
            <h4>Report</h4>
            <p>Generate detailed reports on projects, including activities, budgets, expenses, and deliverables.</p>
        </div>
    </div>
</div>
{% endblock %}

myapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Project Management{% endblock %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'myapp/styles.css' %}">
</head>
<body>
    <header>
        <nav>
            <ul>
                <li class="{% if request.resolver_match.url_name == 'home' %}active{% endif %}">
                    <a href="{% url 'home' %}">Home</a>
                </li>
                <li class="{% if request.resolver_match.url_name == 'about' %}active{% endif %}">
                    <a href="{% url 'about' %}">About</a>
                </li>
            </ul>
        </nav>
    </header>
    <main style="margin-bottom: 0;">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </main>
    <div class="container" style="margin-top: 0;">
        <button class="small-button" onclick="goBack()">Go Back</button>
    </div>
    <script>
        function goBack() {
            window.history.back();
        }
    </script>
</body>
</html>

myapp/templates/choose_object.html
{% extends 'base.html' %}

{% block title %}
Update Element
{% endblock %}

{% block content %}
<div class="container">
    <h1>Choose Object</h1>
    <form method="get" action="{% url 'choose_object' %}">
        {{ form.as_p }}
        <button type="submit">Choose Object</button>
    </form>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const tableSelect = document.getElementById('id_table');
        const attributeSelect = document.getElementById('id_attribute');
        
        function capitalize(str) {
            return str.replace(/\b\w/g, function(char) {
                return char.toUpperCase();
            });
        }
        
        function loadAttributes() {
            const selectedTable = tableSelect.value;
            if (selectedTable) {
                fetch(`/get_attributes/?table=${selectedTable}`)
                    .then(response => response.json())
                    .then(data => {
                        while (attributeSelect.firstChild) {
                            attributeSelect.removeChild(attributeSelect.firstChild);
                        }
                        data.attributes.forEach(attribute => {
                            const option = document.createElement('option');
                            option.value = attribute;
                            option.textContent = capitalize(attribute.replace(/_/g, ' '));
                            attributeSelect.appendChild(option);
                        });
                    });
            } else {
                while (attributeSelect.firstChild) {
                    attributeSelect.removeChild(attributeSelect.firstChild);
                }
            }
        }
        
        tableSelect.addEventListener('change', loadAttributes);
        
        loadAttributes();
    });
</script>
{% endblock %}

myapp/templates/choose_table.html
{% extends 'base.html' %}

{% block title %}
Choose Table
{% endblock %}

{% block content %}
    <h1>Choose Table</h1>
    <form method="post">
        {% csrf_token %} 
        {{ table_form.as_p }}
        <button type="submit">Choose</button>
    </form>
{% endblock %}

myapp/templates/delete.html
{% extends 'base.html' %}

{% block title %}
Delete Element
{% endblock %}

{% block content %}
<div class="container">
    <h1>Delete Element</h1>
    <form method="get" action="{% url 'delete_object' %}" id="deleteForm">
        {% csrf_token %}
        <select name="table" id="id_table">
            {% for choice in form.table.field.choices %}
            <option value="{{ choice.0 }}">{{ choice.1 }}</option>
            {% endfor %}
        </select>
        <select name="attribute" id="id_attribute">
            <option value="">---Choose Attribute---</option>
        </select>
        <input type="text" name="value" id="id_value" placeholder="Value" required>
        <button type="submit">Delete</button>
    </form>
    
    {% if obj_data %}
        <div class="message">
            <h2>Object Deleted:</h2>
            <p>Object has been deleted.</p>
        </div>
    {% endif %}
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const tableSelect = document.getElementById('id_table');
        const attributeSelect = document.getElementById('id_attribute');
        const attributeValueInput = document.getElementById('id_value');
        function capitalize(str) {
            return str.replace(/\b\w/g, function(char) {
                return char.toUpperCase();
            });
        }       
        function loadAttributes() {
            const selectedTable = tableSelect.value;
            if (selectedTable) {
                fetch(`/get_attributes/?table=${selectedTable}`)
                    .then(response => response.json())
                    .then(data => {
                        while (attributeSelect.firstChild) {
                            attributeSelect.removeChild(attributeSelect.firstChild);
                        }
                        data.attributes.forEach(attribute => {
                            const option = document.createElement('option');
                            option.value = attribute;
                            option.textContent = capitalize(attribute.replace(/_/g, ' '));
                            attributeSelect.appendChild(option);
                        });
                    });
            } else {
                while (attributeSelect.firstChild) {
                    attributeSelect.removeChild(attributeSelect.firstChild);
                }
            }
        }
        
        tableSelect.addEventListener('change', loadAttributes);
        
        loadAttributes();
    });
</script>
{% endblock %}

myapp/templates/error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Error</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #fff0f5; 
            margin: 0;
            padding: 20px;
            text-align: center;
        }
        h1 {
            color: #ff0000; 
        }
        p {
            color: #333; 
        }
        .container {
            max-width: 600px;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1);
        }
        button {
            padding: 10px 20px;
            background-color: #007BFF; 
            color: white;
            border: none;
            border-radius: 4px;
            cursor: pointer;
            margin-top: 20px;
        }
        button:hover {
            background-color: #0056b3; 
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>Error</h1>
        <p>{{ error_message }}</p>
        <button onclick="goBack()">Go Back</button>
    </div>

    <script>
        function goBack() {
            window.history.back();
        }
    </script>
</body>
</html>

myapp/templates/generate_report.html
{% extends 'base.html' %}

{% block content %}
<h1>Select Project to Generate Report</h1>
<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Generate Report</button>
</form>
{% endblock %}

myapp/templates/get.html
{% extends 'base.html' %}

{% block title %}
Get Element
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Get Element</h1>
        <form method="get" action="{% url 'get_object' %}">
            {{ form.as_p }}
            <button type="submit">Search</button>
        </form>

        <h2>Search Results:</h2>
            <table class="container">
                <thead>
                    <tr>
                        {% for field_name in field_names %}
                                <th>{{ field_name|capfirst }}</th>
                        {% endfor %}
                    </tr>
                </thead>
                {% if obj_values %}
                <tbody>
                    {% for row in obj_values %}
                        <tr>
                            {% for value in row %}
                                <td>{{ value }}</td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
                {% endif %}
    </div>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const tableSelect = document.getElementById('id_table');
            const attributeSelect = document.getElementById('id_attribute');
            function capitalize(str) {
                return str.replace(/\b\w/g, function(char) {
                    return char.toUpperCase();
                });
            }       
            function loadAttributes() {
                const selectedTable = tableSelect.value;
                if (selectedTable) {
                    fetch(`/get_attributes/?table=${selectedTable}`)
                        .then(response => response.json())
                        .then(data => {
                            while (attributeSelect.firstChild) {
                                attributeSelect.removeChild(attributeSelect.firstChild);
                            }
                            data.attributes.forEach(attribute => {
                                const option = document.createElement('option');
                                option.value = attribute;
                                option.textContent = capitalize(attribute.replace(/_/g, ' '));
                                attributeSelect.appendChild(option);
                            });
                        });
                } else {
                    while (attributeSelect.firstChild) {
                        attributeSelect.removeChild(attributeSelect.firstChild);
                    }
                }
            }
            
            tableSelect.addEventListener('change', loadAttributes);
            
            loadAttributes();
        });
    </script>
{% endblock %}

myapp/templates/home.html
{% extends 'base.html' %}

{% block title %}
Home
{% endblock %}

{% block content %}
<div class="container">
    <div class="flex-container">
        <div class="tools-container">
            <h2>Tools</h2>
            <ul>
                <li><a href="{% url 'show_table' %}">View table</a></li>
                <li><a href="{% url 'choose_table_insert' %}">Insert</a></li>
                <li><a href="{% url 'get_object' %}">Get</a></li>
                <li><a href="{% url 'choose_object' %}">Update</a></li>
                <li><a href="{% url 'delete_object' %}">Delete</a></li>
                <li><a href="{% url 'new_project' %}">New project</a></li>
                <li><a href="{% url 'choose_project' %}">Report</a></li>
            </ul>
        </div>
        
        <div class="projects">
            <h2>Projects</h2>
            {% for project in projects %}
            <div class="project-box" onclick="redirectToManage('Project', '{{ project.project_id }}')">
                    <div class="project-name">{{ project.name }}</div>
                    <div class="column">
                        <div class="row">Id: {{ project.project_id }}</div>
                        <div class="row">Process: {{ project.status }}</div>
                    </div>
            </div>
            {% endfor %}
        </div>
        
        
        <script>
            function redirectToManage(table, projectId) {
                var url = "{% url 'manage' table='__table__' id=0 %}"
                    .replace('__table__', table)
                    .replace(0, projectId);
                location.href = url;
            }
        </script>
        
        
        
        
    </div>
</div>
{% endblock %}